/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [STATE_CODE_EXP]
      ,[SHRP_ID]
      ,[LAYER_NO] AS Layer_Code_No
      ,ISNULL([BINDER_SPEC_GRAV],0) AS BINDER_SPEC_GRAV
      ,ISNULL([BINDER_PCT],0) AS BINDER_PCT
      ,ISNULL([AGG_COARSE_SPEC_GRAV],0) AS AGG_COARSE_SPEC_GRAV 
      ,ISNULL([AGG_COARSE_PCT],0) AS AGG_COARSE_PCT
      ,ISNULL([AGG_FINE_SPEC_GRAV],0) AS AGG_FINE_SPEC_GRAV
      ,ISNULL([AGG_FINE_PCT],0) AS AGG_FINE_PCT
	  ,ISNULL([AGG_FILLER_SPEC_GRAV],0) AS AGG_FILLER_SPEC_GRAV
	  ,ISNULL([AGG_FILLER_PCT],0) AS AGG_FILLER_PCT
FROM [Bucket_30922].[dbo].[TST_SP02]
GROUP BY [STATE_CODE_EXP],[SHRP_ID],[LAYER_NO],[BINDER_SPEC_GRAV],[BINDER_PCT],[AGG_COARSE_SPEC_GRAV]
		,[AGG_COARSE_PCT],[AGG_FINE_SPEC_GRAV],[AGG_FINE_PCT],[AGG_FILLER_SPEC_GRAV],[AGG_FILLER_PCT]
ORDER BY [STATE_CODE_EXP],[SHRP_ID],[LAYER_NO]
